sudo: false
language: python

python:
  - "2.7"
  - "pypy"

env:
  - DJANGO="django==1.8"
  - DJANGO="django==1.9"
  - DJANGO="django==1.10"
  - DJANGO="django==1.11"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coverage==3.7.1 codecov
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W uuslug; fi

script:
  - coverage run --source=djangocms_cameraslider manage.py test

after_success:
  - coveralls
