sudo: false
language: python

python:
  - "3.9"
  - "pypy"

env:
  - DJANGO="django==3.2"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coverage==6.2 codecov
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then pyflakes -x W uuslug; fi

script:
  - coverage run --source=djangocms_cameraslider manage.py test

after_success:
  - coveralls
